name: arabic_proj
channels:
  - conda-forge
dependencies:
  - python=3.13.3
  - pip
  - pip:
      - transformers==4.51.3
      - torch==2.7.0
      - torchaudio==2.7.0
      - accelerate==1.6.0
      - datasets==3.5.1
      - librosa==0.11.0
      - numpy==2.2.5
      - pandas==2.2.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - soundfile==0.13.1
      - safetensors==0.5.3
      - tokenizers==0.21.1
      - huggingface-hub==0.30.1
      - tqdm==4.67.1
      - pyyaml==6.0.2
      - requests==2.32.3
